// Ignore Spelling: Хран Хр Фрдо Фрдонаименование Фрдоразряд Фрдоподтверждение Фло Фио Тфамилия Тотчество Тимя Гис Тимс Ср Спо Сотличием Соответсвие Снилс Скана Рег Пп Прикреп Оксm Кладр Кдиплому Иномер Егэ Дополн Гуп Впо Военн Вобщежитии Вобщежити Вконтакте Вк Асп Академ Озо Озачислении Нпсспо Нпс Мср Мср Лд Ла Кчату Uid Tok Tik Фрдопрограмма

namespace SibSIU.Dean.Database.Entities
{
    public class ВсеСтуденты
    {
        public int Код { get; set; }
        public string Фамилия { get; set; } = null!;
        public string Имя { get; set; } = null!;
        public string? Отчество { get; set; }
        public int? Статус { get; set; }
        public int? КодГруппы { get; set; }
        public string? НомерЗачетнойКнижки { get; set; }
        public short? ГодПоступления { get; set; }
        public string? Пол { get; set; }
        public string? Основания { get; set; }
        public string? ИзучаемыйЯзык { get; set; }
        public bool Долг { get; set; }
        public string? Национальность { get; set; }
        public DateTime? ДатаРождения { get; set; }
        public string? ТипУз { get; set; }
        public string? УчЗаведение { get; set; }
        public string? ГдеНаходитсяУз { get; set; }
        public short? ГодОкончанияУз { get; set; }
        public string? ОтличникУз { get; set; }
        public bool? Пособие { get; set; }
        public string? НомерМедПолиса { get; set; }
        public string? СерияМедПолиса { get; set; }
        public string? СтранаПп { get; set; }
        public string? РегионПп { get; set; }
        public string? ГородПп { get; set; }
        public string? ИндексПп { get; set; }
        public string? УлицаПп { get; set; }
        public string? ДомКвПп { get; set; }
        public string? ТелефонПп { get; set; }
        public string? EMail { get; set; }
        public bool? Общежитие { get; set; }
        public int? НомерОбщежития { get; set; }
        public string? НомерКомнаты { get; set; }
        public string? КемВыдан { get; set; }
        public string? НомерПаспорта { get; set; }
        public DateTime? ДатаВыдачи { get; set; }
        public bool? НаличиеМатери { get; set; }
        public bool? НаличиеОтца { get; set; }
        public string? ФиоМатери { get; set; }
        public string? МестоРабМатери { get; set; }
        public string? ДолжностьМатери { get; set; }
        public string? ФиоОтца { get; set; }
        public string? МестоРабОтца { get; set; }
        public string? ДолжностьОтца { get; set; }
        public byte? ЧислоБратьевИСестер { get; set; }
        public string? СтранаРодители { get; set; }
        public string? РегионРодители { get; set; }
        public string? ГородРодители { get; set; }
        public string? РайонРодители { get; set; }
        public string? ИндексРодители { get; set; }
        public string? УлицаРодители { get; set; }
        public string? ДомКвРодители { get; set; }
        public string? ТелефонРодители { get; set; }
        public bool? Опекунство { get; set; }
        public bool? СостоитВБраке { get; set; }
        public byte? ЧислоДетей { get; set; }
        public string? Примечание { get; set; }
        public string? НомерЛд { get; set; }
        public string? Льготы { get; set; }
        public string? ТипУдостоверения { get; set; }
        public string? СерияАттестата { get; set; }
        public string? НомерАттестата { get; set; }
        public string? ТипОбразДокумента { get; set; }
        public DateTime? ДатаПодачиДокументов { get; set; }
        public string? ПереводДокументов { get; set; }
        public bool? НеМестный { get; set; }
        public int? ГодРождения { get; set; }
        public string? ФормаОбучения { get; set; }
        public string? НаучнаяСпециальность { get; set; }
        public DateTime? ДатаЗачисления { get; set; }
        public string? НомерПриказаОзачислении { get; set; }
        public DateTime? ДатаОкончания { get; set; }
        public string? МестоРаботы { get; set; }
        public string? ПрикрепКафедра { get; set; }
        public string? НаучныйРуководитель { get; set; }
        public string? КандФилософия { get; set; }
        public string? КандИностранный { get; set; }
        public string? КандСпециальность { get; set; }
        public string? Аттестация1 { get; set; }
        public string? Аттестация2 { get; set; }
        public string? Аттестация3 { get; set; }
        public string? Аттестация4 { get; set; }
        public string? ДополнОтпуск { get; set; }
        public string? Командировки { get; set; }
        public long? КодОригинала { get; set; }
        public bool? Село { get; set; }
        public bool? СелоПоПрописке { get; set; }
        public string? КвалификацияСтудента { get; set; }
        public string? Стаж { get; set; }
        public string? Должность { get; set; }
        public DateTime? ПродлениеСессии { get; set; }
        public string? УчебныйПлан { get; set; }
        public bool? Кандидатские { get; set; }
        public bool? Соискатель { get; set; }
        public bool? ДопКвалификация { get; set; }
        public string? Инн { get; set; }
        public string? НомерСоцСтрахования { get; set; }
        public string? НомерДоговора { get; set; }
        public string? Фото { get; set; }
        public bool? Пропуск { get; set; }
        public string? ЧитательскийБилет { get; set; }
        public bool? СокращенноеОбучение { get; set; }
        public bool? ПродленоОбучение { get; set; }
        public string? ПриписноеСвидетельство { get; set; }
        public string? ВоенныйБилет { get; set; }
        public string? ГруппаУчета { get; set; }
        public string? КатегорияУчета { get; set; }
        public string? Состав { get; set; }
        public string? ВоинскоеЗвание { get; set; }
        public string? ВоеннСпециальность { get; set; }
        public string? ВоеннГодность { get; set; }
        public string? Военкомат { get; set; }
        public string? ВоеннСпецУчет { get; set; }
        public string? Гражданство { get; set; }
        public DateTime? ДатыВыдачиАттестата { get; set; }
        public string? БывшаяФамилия { get; set; }
        public bool? Иностранец { get; set; }
        public string? РайонПп { get; set; }
        public string? АкадемСправка { get; set; }
        public string? НомерДиплома { get; set; }
        public DateTime? ДатаРешения { get; set; }
        public DateTime? ДатаВыдачи1 { get; set; }
        public string? РегистрационныйНомер { get; set; }
        public string? ТемаДиплома { get; set; }
        public bool? Заблокирован { get; set; }
        public bool? ВтороеОбразование { get; set; }
        public int? УслОбучения { get; set; }
        public bool? Слушатель { get; set; }
        public bool? СоответсвиеВпо { get; set; }
        public int? КодФакультета { get; set; }
        public bool? ВоеннаяКафедра { get; set; }
        public bool? АкадемСтипендия { get; set; }
        public DateTime? АкадемСтипендияС { get; set; }
        public DateTime? АкадемСтипендияПо { get; set; }
        public bool? СоцСтипендия { get; set; }
        public DateTime? СоцСтипендияС { get; set; }
        public DateTime? СоцСтипендияПо { get; set; }
        public DateTime? ПродленаСессия { get; set; }
        public bool? Озо { get; set; }
        public string? ЛицСчетБанк { get; set; }
        public string? МестоРождения { get; set; }
        public DateTime? ДатаАкадОтпуск { get; set; }
        public int? КодОбщежития { get; set; }
        public int? КодЗаявления { get; set; }
        public string? БывшееИмя { get; set; }
        public DateTime? ДатаНачСессии { get; set; }
        public DateTime? ДатаКонСессии { get; set; }
        public int? Город { get; set; }
        public string? ВоенЗвание { get; set; }
        public string? ВоенОрган { get; set; }
        public string? ВоенМестоСлужбы { get; set; }
        public string? ВоенДолжность { get; set; }
        public string? Логин { get; set; }
        public string? Пароль { get; set; }
        public bool? Признак { get; set; }
        public string? КодПодраздел { get; set; }
        public string? ОбщежитиеДоговор { get; set; }
        public DateTime? ОбщежитиеДата { get; set; }
        public string? ОбщежитиеПл { get; set; }
        public string? Мобильный { get; set; }
        public string? РегНомерДиплома { get; set; }
        public double? СрБаллАттестата { get; set; }
        public bool? Temp { get; set; }
        public DateTime? ДатаАкадОтпускС { get; set; }
        public bool? Староста { get; set; }
        public bool? ГупМср { get; set; }
        public DateTime? ГупМсрДата { get; set; }
        public string? КладрПп { get; set; }
        public string? КладрРодители { get; set; }
        public string? АспНомерПротоколаКафедра { get; set; }
        public string? АспНомерПротоколаФакультет { get; set; }
        public DateTime? АспДатаПротоколаКафедра { get; set; }
        public DateTime? АспДатаПротоколаФакультет { get; set; }
        public int? АспКодНаучногоРуководителя { get; set; }
        public string? ЦерковноеИмя { get; set; }
        public string? Сан { get; set; }
        public string? Skype { get; set; }
        public string? Icq { get; set; }
        public DateTime? ДатаСозданияПароля { get; set; }
        public DateTime? ДатаПоследнегоВхода { get; set; }
        public short? СчетчикПопыток { get; set; }
        public DateTime? ВремяБлокировки { get; set; }
        public bool? ЗаблокированНаСайте { get; set; }
        public string? ПоследнийIp { get; set; }
        public bool УсловныйПеревод { get; set; }
        public int? КодНаучныйРуководитель { get; set; }
        public int? ТипУведомления { get; set; }
        public string? АрхивЛ { get; set; }
        public int? АрхивЕдХр { get; set; }
        public string? АрхивЛа { get; set; }
        public int? АрхивКоличествоЛистов { get; set; }
        public string? АрхивПримечание { get; set; }
        public string? АрхивДопЕдХр { get; set; }
        public int? АрхивНомерОписи { get; set; }
        public int? АрхивНомерКоробки { get; set; }
        public int? АрхивНомерХран { get; set; }
        public int? АрхивЕдХрОбщ { get; set; }
        public string? АрхивДопЕдХрОбщ { get; set; }
        public bool? ГисСтатус { get; set; }
        public DateTime? ГисДата { get; set; }
        public string? Тфамилия { get; set; }
        public string? Тимя { get; set; }
        public string? Тотчество { get; set; }
        public int? КодИзучаемогоИностранногоЯзыка { get; set; }
        public string? Книга { get; set; }
        public bool? ВосстановленИзАрхива { get; set; }
        public string? АрхивЗаметки { get; set; }
        public int? OldUid { get; set; }
        public bool? FromSite { get; set; }
        public bool? IsInAssociation { get; set; }
        public int? ОригинальныйКод { get; set; }
        public Guid? Uid1cStud { get; set; }
        public string? НазваниеДокумента { get; set; }
        public int? КодФрдо2019видыДокумента { get; set; }
        public int? КодФрдо2019статусыДокумента { get; set; }
        public string? ПодтверждениеУтраты { get; set; }
        public string? ПодтверждениеОбмена { get; set; }
        public int? КодФрдо2019уровниОбразования { get; set; }
        public string? СерияДокумента { get; set; }
        public int? НомерДокумента { get; set; }
        public DateTime? ДатаВыдачи2 { get; set; }
        public string? РегистрационныйНомер1 { get; set; }
        public int? КодФрдо2019кодыНпс { get; set; }
        public string? НаименованиеСпециальностиНаправленияПодготовки { get; set; }
        public string? НаименованиеКвалификации { get; set; }
        public string? ОбразовательнаяПрограмма { get; set; }
        public int? ГодПоступления1 { get; set; }
        public int? ГодОкончания { get; set; }
        public int? СрокОбученияЛет { get; set; }
        public int? КодФрдо2019пол { get; set; }
        public int? КодФрдо2019иностранец { get; set; }
        public int? КодФрдо2019формаОбучения { get; set; }
        public string? ВысшееОбразованиеПолучаемоеВпервые { get; set; }
        public int? КодФрдо2019финансированиеОбучения { get; set; }
        public string? НаименованиеДокументаОбОбразованииОригинала { get; set; }
        public string? СерияОригинала { get; set; }
        public int? НомерОригинала { get; set; }
        public string? РегистрационныйNОригинала { get; set; }
        public DateTime? ДатаВыдачиОригинала { get; set; }
        public string? ФамилияПолучателяОригинала { get; set; }
        public string? ИмяПолучателяОригинала { get; set; }
        public string? ОтчествоПолучателяОригинала { get; set; }
        public int? КодФрдо2019кодыНпсспо { get; set; }
        public int? КодФрдо2019уровниОбразованияСпо { get; set; }
        public int? КодФрдо2019видыДокументаСпо { get; set; }
        public string? Снилс { get; set; }
        public bool? IsInSchoolX { get; set; }
        public bool? ЗаблокироватьТесты { get; set; }
        public string? ТемаДипломаПеревод { get; set; }
        public int? КодЭлитногоОбразования { get; set; }
        public string? КвартираПп { get; set; }
        public string? КвартираРодители { get; set; }
        public string? ФормаДокумента { get; set; }
        public bool? НуждаетсяВобщежитии { get; set; }
        public string? EmailForTeams { get; set; }
        public string? Instagram { get; set; }
        public string? TikTok { get; set; }
        public string? ВыпускникиВк { get; set; }
        public DateTime? ВремяДляТимс { get; set; }
        public bool? ШколаХМодератор { get; set; }
        public int? ВконтактеId { get; set; }
        public int? КодФрдо2021финансированиеОбучения { get; set; }
        public string? КодОксm { get; set; }
        public int? КодФрдо2021формаПолученияОбразования { get; set; }
        public string? ПодтверждениеУничтожения { get; set; }
        public string? СерияИномерПриложенияКдиплому { get; set; }
        public string? ПротоколВыдачиДиплома { get; set; }
        public bool? ПолученДипломСотличием { get; set; }
        public DateTime? ДатаПросмотраЛенты { get; set; }
        public bool? ШколаХДоступКчату { get; set; }
        public string? КлючАвторизации { get; set; }
        public double? СрБаллЕгэ { get; set; }
        public string? GoogleId { get; set; }
        public string? ИдентификаторScopus { get; set; }
        public int? СрокОбученияЧасов { get; set; }
        public int? НомерДокументаДляИзменения { get; set; }
        public int? КодФрдоподтверждениеУтраты { get; set; }
        public int? КодФрдоподтверждениеОбмена { get; set; }
        public int? КодФрдоразрядКлассКатегория { get; set; }
        public int? КодФрдопрограммаПрофессиональногоОбучения { get; set; }
        public int? КодФрдонаименованиеПрофессийРабочих { get; set; }
        public string? ВыпускникиПримечанияАдминистратора { get; set; }
        public string? ВыпускникиФакультет { get; set; }
        public int? ЭлитноеОбразованиеКурс { get; set; }
        public DateTime? ВоенныйБилетДата { get; set; }
        public int? КодВоенкомата { get; set; }
        public bool? ВоенкоматПоПриписке { get; set; }
        public bool? ВоенкоматОтсрочка { get; set; }
        public string? ВоенкоматВидУчета { get; set; }
        public byte[]? Версия { get; set; }
        public DateTime? ДатаСменыПароля { get; set; }
        public bool? ПубличноеПортфолио { get; set; }
        public int? ЭлитноеОбразованиеСтатус { get; set; }
        public bool? ОтчисленБезВосстановления { get; set; }
        public Guid? Uid1c { get; set; }
        public string? ИмяСканаФло { get; set; }
        public DateTime? ФлоС { get; set; }
        public DateTime? ФлоПо { get; set; }
        public int? ТипОплатыПроживания { get; set; }
        public bool? ПостоянноПроживаетВобщежити { get; set; }
        public DateTime? ПроживаетВобщежитииС { get; set; }
        public DateTime? ПроживаетВобщежитииПо { get; set; }
        public Guid? Guid { get; set; }
    }
}
